language: node_js
node_js:
  - 12.10.0
dist: trusty
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.19.0
  - export PATH="$HOME/.yarn/bin:$PATH"
script:
    - cd /home/travis/build/jdmac020/goodaleHeadsUp/goodale-heads-up/
    - yarn test